BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {

        private IUnitOfWork _unitOfWork;


        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //GET
        public IActionResult Index()
        {
            //strongly type 
            IEnumerable<CoverType> objCategoryList = _unitOfWork.CoverType.GetAll();


            //pass data obj to View
            return View(objCategoryList);
        }




        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {

            //ถ้า validation ผ่าน not null  ทั้งหมด และ  ต้องไม่มีกรณีที่มี ModelError จากบรรทัด 50
            if (ModelState.IsValid)
            {
                //Add data obj to database
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType created Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Single จะ throw exception ถ้าหาไม่เจอ
            //SingleOrDefault จะไม่ throw exception ถ้าหาไม่เจอ แต่ถ้ามีหลายตัวจะ throw excep
            //FirstOrDefault ถ้าหาเจอตัววแรกจะเอาตัวแรก แต่ถ้าไม่มีไม่ throw excep
            //Find => หาprimary key ของ table

            //var categoryFromDb = _db.Categories.Find(id);
            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {

            //ถ้า validation ผ่าน not null  ทั้งหมด และ  ต้องไม่มีกรณีที่มี ModelError จากบรรทัด 50
            if (ModelState.IsValid)
            {
                //Add data obj to database
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                //เก็บเข้า TempData
                TempData["success"] = "CoverType updated Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Single จะ throw exception ถ้าหาไม่เจอ
            //SingleOrDefault จะไม่ throw exception ถ้าหาไม่เจอ แต่ถ้ามีหลายตัวจะ throw excep
            //FirstOrDefault ถ้าหาเจอตัววแรกจะเอาตัวแรก แต่ถ้าไม่มีไม่ throw excep
            //Find => หาprimary key ของ table

            //var categoryFromDb = _db..Find(id);
            var categoryFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {

            var categoryFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            //Remove data obj to database
            _unitOfWork.CoverType.Remove(categoryFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "CoverType deleted Successfullly";

            //RedirectTo Index
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {

        private IUnitOfWork _unitOfWork;
        //ดึง Depency Injection มาใช้
        private readonly IWebHostEnvironment _hostEnvirontment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvirontment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvirontment = hostEnvirontment;
        }

        //GET
        public IActionResult Index()
        {

            return View();
        }




        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {

            //ถ้า validation ผ่าน not null  ทั้งหมด และ  ต้องไม่มีกรณีที่มี ModelError จากบรรทัด 50
            if (ModelState.IsValid)
            {
                //Add data obj to database
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType created Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }

        //GET
        public IActionResult Upsert(int? id)
        {

            //int? id = คือ param https://localhost:44379/Admin/Product/Upsert?id=1 

            //สร้าง ViewModel แล้วเดะส่งเป็น Object ไปทีเดียวเลย
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            //สร้าง SelectListItem จากคำสั่ง . Select()

            //สร้าง SelectListItem จากคำสั่ง . Select()

            if (id == null || id == 0)
            {
                //create Product

                //ส่งด้วย ViewBag (ปลายทางไม่ต้อง cast Type)
                //ViewBag.CategoryList = CategoryList;
                //ส่งด้วย ViewData (ปลายทางต้อง cast Type)
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            else
            {
                //update Product
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(i => i.Id == id);
            }

       

            return View(productVM);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj,IFormFile file) //IFormFile => UploadFile
        {

            if (ModelState.IsValid)
            {
                //ดึง Path ของ wwwroot มา
                string wwwRootPath = _hostEnvirontment.WebRootPath;
                if (file != null)
                {
                    //ถ้า file ถูก upload มา
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images/products");
                    var extension = Path.GetExtension(file.FileName);

                    //อัพเดทภาพ 
                    if(obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using(var fileStrems = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        //นำ file Copy ไปที่ fileStream
                        file.CopyTo(fileStrems);
                    }
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
                }

                if (obj.Product.Id == 0)
                {
                    //Create
                    _unitOfWork.Product.Add(obj.Product);
                }
                else
                {
                    //Update
                    _unitOfWork.Product.Update(obj.Product);

                }

                _unitOfWork.Save();
                //เก็บเข้า TempData
                TempData["success"] = "Product updated Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }



       

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
            return Json(new {data=productList});
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(c => c.Id == id);
            var categoryFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(c => c.Id == id);
            if (categoryFromDbFirst == null)
            {
                return Json(new { success = false, message = "Error while deleteing" });
            }


            var oldImagePath = Path.Combine(_hostEnvirontment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            //Remove data obj to database
            _unitOfWork.Product.Remove(categoryFromDbFirst);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }
}

BulkyBookWeb/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification"></partial>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Product
            </a>
        </div>
    </div>
    <br />


    <table class="table table-bordered table-striped" style="width:100%" id="tblData">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    ISBN
                </th>
                <th>
                    Price
                </th>
                <th>
                    Author
                </th>
                <th>
                    Category
                </th>
                <th>
                    Operation
                </th>
            </tr>
        </thead>
    </table>

</div>

@section Scripts{
    <script>
        var dataTable;
        $(document).ready(function () {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tblData').DataTable({
                "ajax": {
                    "url": "/Admin/Product/GetAll"
                },
                "columns": [
                    { "data": "title", "width": "15%" },
                    { "data": "isbn", "width": "15%" },
                    { "data": "price", "width": "15%" },
                    { "data": "author", "width": "15%" },
                    { "data": "category.name", "width": "15%" },
                    {
                        "data": "id",
                        "render": function (data) {
                            return `
                                                             <div class="w-78 btn-group" role="group">
                                                                <a href="/Admin/Product/Upsert?id=${data}" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit</a>
                                                                <a  onClick=Delete('/Admin/Product/Delete/${data}')  class="btn btn-danger mx-2"><i class="bi bi-trash3"></i> Delete</a>
                                                            </div>
                                                           `
                        },
                        "width": "15%"
                    },
                ]
            });

        }

        function Delete(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    fetch(url,{method:'DELETE'})
                        .then(function (response) {
                            return response.json();
                        })
                        .then(function (data) {
                            // Do something with the response
                            if (data.success) {
                                dataTable.ajax.reload();
                                toastr.success(data.message)
                            } else {
                                toastr.error(data.message)
                            }
                        });
                }
            })
        }
    </script>
}

BulkyBookWeb/Areas/Admin/Views/Product/Upsert.cshtml
@model BulkyBook.Models.ViewModels.ProductVM



<!--enctype เอาไว้ work with Upload File-->
<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Product.Id" hidden />
    <input asp-for="Product.ImageUrl" hidden />

    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Product.Id != 0 ? "Update" : "Create") Product</h2>
                    <hr />
                </div>
                <div asp-validation-summary="All"></div>
                <div class="mb-3">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Title"></label>
                    <input asp-for="Product.Title" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Description"></label>
                    <textarea asp-for="Product.Description" class="form-control" rows="3"></textarea>
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Description" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.ISBN"></label>
                    <input asp-for="Product.ISBN" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.ISBN" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Author"></label>
                    <input asp-for="Product.Author" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Author" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.ListPrice"></label>
                    <input asp-for="Product.ListPrice" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.ListPrice" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Price"></label>
                    <input asp-for="Product.Price" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Price" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Price50"></label>
                    <input asp-for="Product.Price50" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Price50" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.Price100"></label>
                    <input asp-for="Product.Price100" class="form-control" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.Price100" class="text-danger"></span>
                </div>
                <div class="mb-3 col-12">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.ImageUrl"></label>
                    <input type="file" class="form-control" id="uploadBox" name="file" />
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.CategoryId"></label>
                    <select asp-for="Product.CategoryId" asp-items="@Model.CategoryList" class="form-select">
                        <option disabled selected>--Select Category--</option>
                    </select>
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
                    <label asp-for="Product.CoverTypeId"></label>
                    <select asp-for="Product.CoverTypeId" asp-items="@Model.CoverTypeList" class="form-select">
                        <option disabled selected>--Select CoverType--</option>
                    </select>
                    <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
                    <span asp-validation-for="Product.CoverTypeId" class="text-danger"></span>
                </div>
                <div class="col-12">
                    @if (Model.Product.Id != 0)
                    {
                    //Update
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    }
                    else
                    {
                //Create
                        <button type="submit" class="btn btn-primary" style="width:150px" onclick="return ValidateInput()">Create</button>
                    }

                    <a asp-asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back</a>
                </div>

            </div>

        </div>
        <div class="col-2 pt-4">
            <img  src="@Model.Product.ImageUrl" width="100%"
            style="border-radius:5px;border:1px solid #bbb9b9"/>
        </div>
    </div>

</form>

@section Scripts{
    @* validation Client side  ถ้า validation ไม่ผ่านจะไม่ส่งไปให้ server เลย *@
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>

        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ]
        });

        function ValidateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Please upload an Image!',
                });
                return false;
            }
            return true;
        }
    </script>
}