BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private IUnitOfWork _unitOfWork;


        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //GET
        public IActionResult Index()
        {
            //strongly type 
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();


            //pass data obj to View
            return View(objCategoryList);
        }




        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //Validation ไม่ผ่าน (Server side Validation)
            //Custom Validation
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                //ถ้า key เป็นชื่อเดียวกับ model ทำให้ validation ใต้ field นั้นได้เลย
                //Name=name
                ModelState.AddModelError("DisplayOrder", "The DisplayOrder cannot exatly match the Name.");
            }

            //ถ้า validation ผ่าน not null  ทั้งหมด และ  ต้องไม่มีกรณีที่มี ModelError จากบรรทัด 50
            if (ModelState.IsValid)
            {
                //Add data obj to database
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category created Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Single จะ throw exception ถ้าหาไม่เจอ
            //SingleOrDefault จะไม่ throw exception ถ้าหาไม่เจอ แต่ถ้ามีหลายตัวจะ throw excep
            //FirstOrDefault ถ้าหาเจอตัววแรกจะเอาตัวแรก แต่ถ้าไม่มีไม่ throw excep
            //Find => หาprimary key ของ table

            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault( c => c.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            //Validation ไม่ผ่าน (Server side Validation)
            //Custom Validation
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                //ถ้า key เป็นชื่อเดียวกับ model ทำให้ validation ใต้ field นั้นได้เลย
                //Name=name
                ModelState.AddModelError("DisplayOrder", "The DisplayOrder cannot exatly match the Name.");
            }

            //ถ้า validation ผ่าน not null  ทั้งหมด และ  ต้องไม่มีกรณีที่มี ModelError จากบรรทัด 50
            if (ModelState.IsValid)
            {
                //Add data obj to database
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                //เก็บเข้า TempData
                TempData["success"] = "Category updated Successfullly";

                //RedirectTo Index
                return RedirectToAction("Index");
            }
            //หากValidation ไม่ผ่านส่งหน้าจอเดิมกลับและส่ง obj ตัวนี้ไปเพื่อไปแสดงใน tag span ใน tag-helper 
            return View(obj);

        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Single จะ throw exception ถ้าหาไม่เจอ
            //SingleOrDefault จะไม่ throw exception ถ้าหาไม่เจอ แต่ถ้ามีหลายตัวจะ throw excep
            //FirstOrDefault ถ้าหาเจอตัววแรกจะเอาตัวแรก แต่ถ้าไม่มีไม่ throw excep
            //Find => หาprimary key ของ table

            //var categoryFromDb = _db..Find(id);
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault((System.Linq.Expressions.Expression<Func<Category, bool>>)(c => c.Id == id));
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {

            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault((System.Linq.Expressions.Expression<Func<Category, bool>>)(c => c.Id == id));
            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            //Remove data obj to database
            _unitOfWork.Category.Remove(categoryFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted Successfullly";

            //RedirectTo Index
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/Category/Create.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back</a>
    </div>
</form>

@section Scripts{
    @* validation Client side  ถ้า validation ไม่ผ่านจะไม่ส่งไปให้ server เลย *@
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/Category/Delete.cshtml
@model Category


<!-- asp-action คือบอกว่าจะยิงไปที่ Action ไหน  -->
<form method="post" asp-action="Delete">
    <!--  id ไว้ลบ -->
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr />
        </div>
        <div class="mb-3">
            <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled/>
        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" disabled/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back</a>
    </div>
</form>

@section Scripts{
    @* validation Client side  ถ้า validation ไม่ผ่านจะไม่ส่งไปให้ server เลย *@
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/Category/Edit.cshtml
@model Category

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <!--asp-for เป็น tag helper ใช้สำหรับ bilding Name กับตัวแปรใน Model เลย-->
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <!--asp-validation-for เป็น tag helper ใช้สำหรับแสดงข้อความ error ที่ส่งมาจาก serverside-->
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back</a>
    </div>
</form>

@section Scripts{
    @* validation Client side  ถ้า validation ไม่ผ่านจะไม่ส่งไปให้ server เลย *@
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/Category/Index.cshtml
@model IEnumerable<Category>

@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification"></partial>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Category
            </a>
        </div>
    </div>
    <br />


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Category Name
                </th>
                <th>
                    Display Order
                </th>
                <th>
                    Operation
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    <tr>
                        <td width="50%">
                            @item.Name
                        </td>
                        <td width="30%">
                            @item.DisplayOrder
                        </td>
                         <td>
                            <div class="w-78 btn-group" role="group">
                                <a asp-controller="Category" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit</a>
                                <a asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3"></i> Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>

</div>